### ISSUE TITLE
Visual Studio 15 support

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/VisualFSharpPowerTools#1370]

**Comment by vasily-kirichenko** [comment]
go ahead.

**Comment by xperiandri** [comment]
Is there a sample project on which I can test all the features?
I just updated manifest and it works in VS 15 but I cannot be sure that all the features work.

**Comment by vasily-kirichenko** [comment]
Why don't you test it on *any* project?

**Comment by xperiandri** [comment]
I have 2. But they don't have all conditions for all features. I will need to simulate them.

**Comment by jackfoxy** [comment]
After VS2015 update 2 I no longer see the navigation bar. I tried turning the option off and turning it back on, but that does not fix it.

**Comment by xperiandri** [comment]
Works fine within Visual Studio 2015 Update 2 and in 15 Preview
Try devenv /setup

**Comment by jackfoxy** [comment]
Nav bar has reappeared in one environment...
Ignore for now, must be something on my end.

**Comment by calwi** [comment]
Same problem after Update 2 install, Navigation Bar had vanished from the options. I downloaded a new copy of the vsix to reinstall... removed the extension completely... now installer only gives option for VS2013 (which is also on the machine). So I don't have anything. Nor can I find it from within VS Tools & Extensions.

**Comment by xperiandri** [comment]
Open it with 7-zip
Edit extension.vsixmanifest
```
    <InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="[13.0,16.0)" />
...
    <Dependency Id="FSharp.Editor" DisplayName="Microsoft Visual FSharp Editor Extensions" Version="[12.0,16.0)" Location="http://www.microsoft.com/en-us/download/details.aspx?id=48179" />
```
Close editor
Save
Install

**Comment by calwi** [comment]
Sorry for not getting back sooner. @xperiandri solution hasn't worked. I'll try this from scratch on a fresh vm and install and see if anything alters.

**Comment by xperiandri** [comment]
Pick Definition is grayed out.
Displays 2015 only

**Comment by xperiandri** [comment]
```
System.Exception: Unsupported Visual Studio version: Unknown at FSharpVSPowerTools.ProjectSystem.VisualStudioVersionModule.toBestMatchFSharpVersion@47.Invoke(String message) at FSharpVSPowerTools.Linting.LintTagger..ctor(ITextDocument textDocument, VSLanguageService vsLanguageService, IServiceProvider serviceProvider, ProjectFactory projectFactory, IOpenDocumentsTracker openDocumentsTracker) at FSharpVSPowerTools.LintTaggerProvider.<>c__DisplayClass6_0`1.<CreateTagger>b__0() at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator) at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Func`1 creator) at FSharpVSPowerTools.LintTaggerProvider.CreateTagger[T](ITextView textView, ITextBuffer buffer) at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
```

**Comment by dungpa** [comment]
@xperiandri Try latest build https://ci.appveyor.com/project/dungpa/visualfsharppowertools/branch/master/artifacts. This has been fixed for a few days.

**Comment by calwi** [comment]
This is now installing to VS2015 after Update 2... so great. Although still missing the Navigation Bar option, which was the original issue. Everything else working fine.

**Comment by vasily-kirichenko** [comment]
@calwi Navigation Bar is not supported anymore 'coz VFT will remove it entirely. We will have to port it into VFPT.

**Comment by calwi** [comment]
OK. Thanks for the info. I don't fully understand what that means... I'm guessing something to do with MSFT. What is VFT and VFPT? The latter is the Power Tools, so this project? The former is Visual Studio F# Team? Who is removing it and why? It's quite useful.

**Comment by vasily-kirichenko** [comment]
VFT is Visual F# Tools - the F# compiler and its VS integration, it's developed by Microsoft. VFPT - this project.

The Navigation Bar was always a part of VFT, but it was considered a somewhat unstable feature and was not turned on by default. To enable it, one had to add a special parameter to `devenv.exe.config`. So, everything VFPT did was setting that parameter. When VS 2015 RTM was released a bug was found: modifying the config led to VS being unstable or something like that (I don't remember really). So, the MS team decided to remove the NavBar entirely, so we removed the setting from VFPT, too. 

The only way to resurrect NavBar is to port the original code into this project. Nobody has claimed interest to do it yet.

**Comment by calwi** [comment]
Right. Thanks for clearing that up. Hopefully one day then perhaps. :) Cheers.

**Comment by xperiandri** [comment]
@dungpa, for now that build works fine

**Comment by jackfoxy** [comment]
I succeeded in getting the Nav Bar working in VS 2015 update 2 by adding
````<appSettings>
			<add key="fsharp-navigationbar-enabled" value="true" />
			<add key="fsharp-regions-enabled" value="true" />
        </appSettings>
````
to the IDE config file, as I think @vasily-kirichenko suggested on another issue thread.
Works so far with F# and Typescript. I don't know what the issue is/was the VS team had.
